spring.application.name=canvasia
spring.datasource.url=jdbc:postgresql://localhost:5432/canvasia_db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=