spring.application.name=canvasia
spring.datasource.url=jdbc:postgresql://localhost:5432/canvasia_db
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
jwt.refresh-expiration=604800000
google.auth.client-id=

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

cloudinary.cloud-name=dyygjfco1
cloudinary.api-key=962236868779913
cloudinary.api-secret=DGSKfDxxMK-NtyMYAKlpa-lmbTY
cloudinary.folder=avatars
cloudinary.avatar.delivery-width=512