spring.application.name=canvasia

#Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8081}

#JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

#OTP
app.otp.length=6
app.otp.expiration-minutes=5

#OAuth2
app.oauth2.enabled=false
app.oauth2.frontend-base-url=${FE_BASE_URL}
google.auth.client-id=${GOOGLE_AUTH_CLIENT_ID}

# Multipart
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY}
cloudinary.api-secret=${CLOUDINARY_SECRET}
cloudinary.folder=canvasia/avatars
cloudinary.avatar.delivery-width=512
cloudinary.post.original-folder=canvasia/original
cloudinary.post.thumbnail-folder=canvasia/thumbnail

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.moderation.queue=ai.moderation